name: check-unitest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Cache cargo
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.92.0
          components: rustfmt,clippy

      - name: install taplo
        uses: baptiste0928/cargo-install@v3
        with:
          crate: taplo-cli

      - name: setup env
        run: |
          pip3 install pre-commit

      - name: Check formatting
        run: |
          pre-commit run -a
      #
      # - name: Lint
      #   run: cargo clippy --workspace --all-targets

      - name: Build
        run: cargo build --verbose
